### ISSUE TITLE
Delete HashID

### ISSUE THREAD

**Issue by zefr0x** [n0kovo/awesome-password-cracking#6]
https://github.com/n0kovo/awesome-password-cracking/blob/fb295408824f818f840f1ebbccbf6b98da886fa6/README.md?plain=1#L146

No longer maintained since 2015

[Name That Hash](https://github.com/HashPals/Name-That-Hash) is already on this list and it's the currently maintained and approved fork of it: https://github.com/psypanda/hashID/issues/50.

**Comment by n0kovo** [comment]
Thanks! 976c7c38ce8bd4ddbbd59b364e83ff54bc833f49
